spring:
  config:
    import: optional:file:.env[.properties]
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-sonnet-4-5-20250929  # or claude-opus-4.1
          temperature: 0.7 #창의력 0.0~0.9 슷자가 높을수록 창의력 발휘
          max-tokens: 4096
    ollama:
      base-url: http://localhost:11434  # OLLAMA 서버 주소*
      chat:
        options:
          model: qwen2.5:3b              # 사용할 모델*
          temperature: 0.7               # 창의성 (0.0 ~ 1.0)
          num-predict: 1000              # 최대 생성 토큰 수# 로깅 설정 (선택사항)
          keep-alive: 5m  # 5분간 모델을 메모리에 유지
  flyway:
    enabled: true # Flyway 활성화
    # 마이그레이션 파일 위치 지정 (기본값)
    locations: classpath:db/migration # 마이그레이션 SQL 파일이 위치할 경로
    baseline-on-migrate: true # 기존에 테이블이 있는 DB에 Flyway를 처음 적용할 때 사용
    # 데이터베이스 연결 설정
  datasource:
      url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 5  # 최대 커넥션 개수
        connection-timeout: 30000 # 커넥션을 얻기 위해 대기하는 최대 시간 (ms)
        max-lifetime: 1800000 # 커넥션의 최대 수명 (ms)

  # JPA 및 Hibernate 설정
  jpa:
    # show_sql: JPA 실행시 작동하는 SQL이 콘솔에 표시된다
    show_sql: true
    hibernate:
      # ddl-auto: 애플리케이션 실행 시 스키마(테이블) 처리 전략
        # none: 아무 작업도 하지 않음 (운영 환경 추천)
        # create: 기존 테이블 삭제 후 다시 생성
        # update: 변경된 부분만 반영
      ddl-auto: none # 개발: update, 프로덕션: validate
    properties:
      hibernate:
        # MySQL 8 버전에 맞는 Dialect(방언) 설정
        dialect: org.hibernate.dialect.MySQL8Dialect

  # 로깅 레벨 설정
  logging:
    level:
      # Hibernate가 실행하는 SQL 쿼리를 DEBUG 레벨로 로그에 출력
      org.hibernate.SQL: DEBUG

  # 내장 웹 서버 설정
  server:
    port: 8080

points:
  default-rate: 0.01
  vip-rate: 0.015
  category-rate-map:
    electronics: 0.015
    book: 0.02
    food: 0.01
  min-usage-amount: 10000
  min-usage-point: 100
  expire-days: 365
  max-balance: 1000000

cart:
  max-items: 50
  promotion-multipliers:
    welcome: 1.2
    vipfest: 1.5
